// components/Header.jsx
import Link from 'next/link';
import { useState } from 'react';

import MenuToggle from './MenuToggle/MenuToggle';
import ModalMenuMobile from './Modals/ModalMenuMobile';
import ThemeButton from './ThemeButton';

export default function Header({ pageTitle }) {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  return (
    <>
      <header className="w-full border-b dark:border-gray-600 fixed top-0 bg-white dark:bg-black z-10">
        <div className="max-w-6xl h-16 md:h-20 px-4 md:px-6 lg:px-8 flex justify-between items-center mx-auto">
          <Link href="/">
            <a className="nav-link">JuanCamiloQhz</a>
          </Link>
          <div className="hidden md:flex gap-4 dark:text-gray-100">
            <Link href="/">
              <a className="nav-link">Home</a>
            </Link>
            <Link href="/blog">
              <a className="nav-link">Blog</a>
            </Link>
            <Link href="/work">
              <a className="nav-link">Work</a>
            </Link>
            <Link href="/about">
              <a className="nav-link">About</a>
            </Link>
            <Link href="/contact">
              <a className="nav-link">Contact</a>
            </Link>
            <ThemeButton />
          </div>
          <div className="flex items-center md:hidden">
            <button
              type="button"
              className="p-0 border-0"
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            >
              <MenuToggle isOpen={mobileMenuOpen} />
            </button>
          </div>
        </div>
      </header>
      {pageTitle && (
        <div className="mt-16 md:mt-20 w-full h-24 md:h-28 flex items-center border-b dark:border-gray-600 bg-white dark:bg-black">
          <div className="px-4 md:px-6 ld:px-8 max-w-6xl mx-auto w-full flex items-center">
            <h1>{pageTitle}</h1>
          </div>
        </div>
      )}
      <ModalMenuMobile
        isOpen={mobileMenuOpen}
        onClose={() => setMobileMenuOpen(false)}
      />
    </>
  );
}

// apps/sveltekit/src/lib/components/Header.svelte
<script>
	import NavItem from './NavItem.svelte';

	import ThemeSwitch from './ThemeSwitch.svelte';
</script>

<!-- <ThemeSwitch /> -->

<header class="w-full top-0 z-10 px-6 md:px-8">
	<div class="max-w-3xl w-full h-20 md:h-24  flex justify-between items-center mx-auto">
		<div class="flex items-center justify-between w-full">
			<button
				type="button"
				class="p-0 border-0 m-0 flex items-center justify-center rounded-full sm:hidden hover:bg-transparent"
				on:click={() => console.log('holi')}
			>
				menutoggle
				<!-- <MenuToggle isOpen={mobileMenuOpen} size={20} /> -->
			</button>
			<ul class="hidden sm:flex items-center mr-5 ml-[-0.60rem]">
				<NavItem href="/">Home</NavItem>
				<NavItem href="/blog">Blog</NavItem>
				<NavItem href="/work">Work</NavItem>
				<NavItem href="/about">About</NavItem>
				<NavItem href="/contact">Contact</NavItem>
			</ul>
			<div class="flex items-center">
				<span>Locale</span>
				<!-- <LocaleSwitcher /> -->
				<!-- <ThemeButton /> -->
				<span>themebutton</span>
			</div>
		</div>
	</div>
</header>
